version: "3.9"
services:
  app:
    build: .
    restart: always
    networks:
      - app_net
    env_file:
      - .env
    links:
      - mysql
    ports:
      - "5000:5000"
    volumes:
      - ./token:/token

  mysql:
    image: mysql
    networks:
      - app_net
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
networks:
  app_net:
    driver: bridge